import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Sparkles, RefreshCw, CalendarRange, Mail } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { format, subDays } from "date-fns";
import { toast } from "sonner";

interface Props {
  scope: string; // dept name or 'all'
  tasks: any[];
  profiles: any[];
}

const CACHE_KEY = (scope: string) => `rac-weekly-ai-${scope}`;
const ONE_HOUR = 60 * 60 * 1000;

export function WeeklyAISummaryCard({ scope, tasks, profiles }: Props) {
  const [summary, setSummary] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [generatedAt, setGeneratedAt] = useState<number | null>(null);

  const compute = async (force = false) => {
    const cacheKey = CACHE_KEY(scope);
    if (!force) {
      try {
        const raw = localStorage.getItem(cacheKey);
        if (raw) {
          const parsed = JSON.parse(raw);
          if (Date.now() - parsed.t < ONE_HOUR) {
            setSummary(parsed.s);
            setGeneratedAt(parsed.t);
            return;
          }
        }
      } catch {}
    }
    setLoading(true);
    try {
      const sevenAgo = subDays(new Date(), 7);
      const recent = (tasks || []).filter(t => t.updated_at && new Date(t.updated_at) >= sevenAgo);
      const completedThisWeek = recent.filter(t => t.status === "completed").length;
      const overdueNow = (tasks || []).filter(t => t.status === "overdue").length;
      const inProgress = (tasks || []).filter(t => t.status === "in-progress").length;
      const staffCount = (profiles || []).length;
      const topDoers = (profiles || [])
        .map(p => ({
          name: p.full_name,
          done: recent.filter(t => (t.assigned_to === p.full_name || t.assigned_to_user_id === p.id) && t.status === "completed").length,
        }))
        .sort((a, b) => b.done - a.done)
        .slice(0, 3)
        .filter(x => x.done > 0);

      const payload = {
        scope,
        windowDays: 7,
        completedThisWeek,
        overdueNow,
        inProgress,
        staffCount,
        topDoers,
      };

      const prompt = `You are a Fortune 500 Chief of Staff. Write a crisp, executive-grade WEEKLY DIGEST for the workforce scope "${scope}" using ONLY this JSON: ${JSON.stringify(payload)}.

Return EXACTLY four short bullet points, each starting with a verb:
• Highlights — 1 sentence on what went well this week.
• Risks — 1 sentence on what's slipping (overdue / bottlenecks).
• People — name top 1–2 doers if any, otherwise note "no standouts".
• Next 7 days — 1 specific recommended action.

No markdown bold/asterisks. No preamble. No closing line. Max 90 words total.`;

      const { data, error } = await supabase.functions.invoke("ai-assistant", {
        body: { messages: [{ role: "user", content: prompt }] },
      });
      if (error) throw error;
      const text = (data?.content || "Weekly summary unavailable.").replace(/\*\*/g, "").replace(/\*/g, "").trim();
      setSummary(text);
      const t = Date.now();
      setGeneratedAt(t);
      try { localStorage.setItem(cacheKey, JSON.stringify({ t, s: text })); } catch {}
    } catch (e: any) {
      console.error("Weekly AI summary error:", e);
      setSummary("Unable to generate weekly digest right now. Try again in a moment.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { compute(); /* eslint-disable-next-line */ }, [scope, tasks?.length, profiles?.length]);

  const copyToEmail = () => {
    const subject = encodeURIComponent(`Weekly Workforce Digest — ${scope} — ${format(new Date(), "d MMM yyyy")}`);
    const body = encodeURIComponent(summary + "\n\n— Generated by REDtech AI Assistant");
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  return (
    <Card className="mb-8 border-border/40 bg-gradient-to-br from-primary/5 via-card to-card shadow-lg overflow-hidden relative">
      <div className="absolute -top-12 -right-12 opacity-[0.06] pointer-events-none">
        <Sparkles className="w-56 h-56" />
      </div>
      <CardHeader className="border-b border-border/30 pb-4 relative z-10">
        <div className="flex items-start justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-primary/15 flex items-center justify-center border border-primary/20">
              <CalendarRange className="h-5 w-5 text-primary" />
            </div>
            <div>
              <CardTitle className="text-lg font-black tracking-tight flex items-center gap-2">
                AI Weekly Summary
                <Badge className="bg-primary text-white hover:bg-primary border-none scale-90">7-DAY DIGEST</Badge>
              </CardTitle>
              <p className="text-[11px] text-muted-foreground font-medium">
                {generatedAt ? `Generated ${format(generatedAt, "EEE d MMM, HH:mm")} · cached 1h` : "Generating…"}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button type="button" variant="outline" size="sm" onClick={() => compute(true)} disabled={loading} className="h-8 text-[11px] font-bold uppercase tracking-wider">
              <RefreshCw className={`h-3.5 w-3.5 mr-1.5 ${loading ? "animate-spin" : ""}`} /> Refresh
            </Button>
            <Button type="button" variant="outline" size="sm" onClick={copyToEmail} disabled={!summary || loading} className="h-8 text-[11px] font-bold uppercase tracking-wider">
              <Mail className="h-3.5 w-3.5 mr-1.5" /> Email
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent className="p-6 relative z-10">
        {loading && !summary ? (
          <div className="flex items-center gap-3 text-sm text-muted-foreground">
            <span className="w-3 h-3 rounded-full border-2 border-primary/40 border-t-primary animate-spin" />
            Distilling the last 7 days into an executive digest…
          </div>
        ) : (
          <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-foreground/90 max-w-4xl">{summary}</pre>
        )}
      </CardContent>
    </Card>
  );
}
